### ISSUE TITLE
Latest NS data is incomplete and causes an error

### ISSUE THREAD

**Issue by korsvanloon** [waagsociety/scholen#1]
The build of the OpenTripPlannerGraph breaks for `gtfs-iffns-latest.zip` (which is the same as `gtfs-iffns-20121010.zip`) because the agency.txt csv file lacks agency_urls for the last two entries.

```
09:25:09.047 INFO (OTPConfigurator.java:126) Wiring up and configuring graph builder task.
09:25:09.200 INFO (MavenVersion.java:53) Parsed Maven artifact version: 1.0.0-SNAPSHOT => MavenVersion(1, 0, 0, SNAPSHOT, 9605323e3940570f43f4c9cb9f569e19f0e134a6) UID=-1000000
09:25:09.311 INFO (OTPConfigurator.java:133) Searching for graph builder input files in ./otp/data
09:25:09.344 INFO (OTPConfigurator.java:142) Found GTFS file ./otp/data/gtfs-iffns-latest.zip
09:25:09.345 INFO (OTPConfigurator.java:142) Found GTFS file ./otp/data/gtfs-kv1connexxion-latest.zip
09:25:09.355 INFO (OTPConfigurator.java:142) Found GTFS file ./otp/data/gtfs-kv1ebs-latest.zip
09:25:09.355 INFO (OTPConfigurator.java:142) Found GTFS file ./otp/data/gtfs-kv1gvb-latest.zip
09:25:09.519 INFO (GtfsGraphBuilderImpl.java:181) reading GTFS bundle at ./otp/data/gtfs-iffns-latest.zip
09:25:09.542 INFO (GtfsGraphBuilderImpl.java:195) reading entities: org.onebusaway.gtfs.model.Agency
Exception in thread "main" org.onebusaway.csv_entities.exceptions.CsvEntityIOException: io error: entityType=org.onebusaway.gtfs.model.Agency path=agency.txt lineNumber=16
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:161)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:120)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:115)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:108)
    at org.opentripplanner.graph_builder.impl.GtfsGraphBuilderImpl.loadBundle(GtfsGraphBuilderImpl.java:196)
    at org.opentripplanner.graph_builder.impl.GtfsGraphBuilderImpl.buildGraph(GtfsGraphBuilderImpl.java:141)
    at org.opentripplanner.graph_builder.GraphBuilderTask.run(GraphBuilderTask.java:141)
    at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:62)
Caused by: org.onebusaway.csv_entities.exceptions.MissingRequiredFieldException: missing required field: agency_url
    at org.onebusaway.csv_entities.schema.AbstractFieldMapping.isMissingAndOptional(AbstractFieldMapping.java:100)
    at org.onebusaway.csv_entities.schema.DefaultFieldMapping.translateFromCSVToObject(DefaultFieldMapping.java:43)
    at org.onebusaway.csv_entities.IndividualCsvEntityReader.readEntity(IndividualCsvEntityReader.java:129)
    at org.onebusaway.csv_entities.IndividualCsvEntityReader.handleLine(IndividualCsvEntityReader.java:96)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:157)
    ... 7 more
```

This is the content of that agency file:

```
agency_id,agency_name,agency_url,agency_timezone,agency_lang
22,GVB,http://www.gvb.nl,Europe/Amsterdam,nl
911,Keolis,http://www.keolis.de,Europe/Amsterdam,nl
500,Arriva,http://www.arriva.nl,Europe/Amsterdam,nl
310,EETC,http://www.eetc.nl,Europe/Amsterdam,nl
910,DB,http://www.db.de,Europe/Amsterdam,nl
920,NMBS,http://www.nmbs.be,Europe/Amsterdam,nl
700,Veolia,http://www.veolia.nl,Europe/Amsterdam,nl
400,Syntus,http://www.syntus.nl,Europe/Amsterdam,nl
100,NS,http://www.ns.nl,Europe/Amsterdam,nl
200,NS International,http://www.ns-hispeed.nl,Europe/Amsterdam,nl
300,Thalys,http://www.thalys.nl,Europe/Amsterdam,nl
501,Hermes,http://www.breng.nl,Europe/Amsterdam,nl
52,Breng,http://www.breng.nl,Europe/Amsterdam,nl
54,Valleilijn,http://www.valleilijn.nl,Europe/Amsterdam,nl
751,U-OV,,Europe/Amsterdam,nl
951,Eurostar,,Europe/Amsterdam,nl
```

The build succeeds with a previous version of the NS data: `gtfs-iffns-20121015.zip`.

You might either want to edit the instructions or catch this edge case in the building proces.

**Comment by bertspaan** [comment]
Added README section in cf8916cfa44a917ac7c72e36a11ee94921919b8d.
